//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClientTRICLib.wsIntegration {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServiceIntegrator", Namespace="http://tempuri.org/")]
    public partial class ServiceIntegrator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOperationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOperationParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperationByIdInvokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback OperationByNameInvokeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAuthorizationTicketOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceIntegrator(string url) {
            this.Url = url;
            //this.Url = global::ClientTRICLib.Properties.Settings.Default.ClientTRICLib_wsIntegration_ServiceIntegrator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOperationsCompletedEventHandler GetOperationsCompleted;
        
        /// <remarks/>
        public event GetOperationParamsCompletedEventHandler GetOperationParamsCompleted;
        
        /// <remarks/>
        public event OperationByIdInvokeCompletedEventHandler OperationByIdInvokeCompleted;
        
        /// <remarks/>
        public event OperationByNameInvokeCompletedEventHandler OperationByNameInvokeCompleted;
        
        /// <remarks/>
        public event GetAuthorizationTicketCompletedEventHandler GetAuthorizationTicketCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceIntegrator/GetOperations", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")]
        public Operation[] GetOperations() {
            object[] results = this.Invoke("GetOperations", new object[0]);
            return ((Operation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOperationsAsync() {
            this.GetOperationsAsync(null);
        }
        
        /// <remarks/>
        public void GetOperationsAsync(object userState) {
            if ((this.GetOperationsOperationCompleted == null)) {
                this.GetOperationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperationsOperationCompleted);
            }
            this.InvokeAsync("GetOperations", new object[0], this.GetOperationsOperationCompleted, userState);
        }
        
        private void OnGetOperationsOperationCompleted(object arg) {
            if ((this.GetOperationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOperationsCompleted(this, new GetOperationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceIntegrator/GetOperationParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")]
        public OperationParam[] GetOperationParams(int operationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool operationIdSpecified) {
            object[] results = this.Invoke("GetOperationParams", new object[] {
                        operationId,
                        operationIdSpecified});
            return ((OperationParam[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOperationParamsAsync(int operationId, bool operationIdSpecified) {
            this.GetOperationParamsAsync(operationId, operationIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetOperationParamsAsync(int operationId, bool operationIdSpecified, object userState) {
            if ((this.GetOperationParamsOperationCompleted == null)) {
                this.GetOperationParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOperationParamsOperationCompleted);
            }
            this.InvokeAsync("GetOperationParams", new object[] {
                        operationId,
                        operationIdSpecified}, this.GetOperationParamsOperationCompleted, userState);
        }
        
        private void OnGetOperationParamsOperationCompleted(object arg) {
            if ((this.GetOperationParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOperationParamsCompleted(this, new GetOperationParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceIntegrator/OperationByIdInvoke", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet OperationByIdInvoke([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ticket, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] int[] operationIDKeys, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")] OperationValue[] requestParamValues) {
            object[] results = this.Invoke("OperationByIdInvoke", new object[] {
                        ticket,
                        operationIDKeys,
                        requestParamValues});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OperationByIdInvokeAsync(string ticket, int[] operationIDKeys, OperationValue[] requestParamValues) {
            this.OperationByIdInvokeAsync(ticket, operationIDKeys, requestParamValues, null);
        }
        
        /// <remarks/>
        public void OperationByIdInvokeAsync(string ticket, int[] operationIDKeys, OperationValue[] requestParamValues, object userState) {
            if ((this.OperationByIdInvokeOperationCompleted == null)) {
                this.OperationByIdInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperationByIdInvokeOperationCompleted);
            }
            this.InvokeAsync("OperationByIdInvoke", new object[] {
                        ticket,
                        operationIDKeys,
                        requestParamValues}, this.OperationByIdInvokeOperationCompleted, userState);
        }
        
        private void OnOperationByIdInvokeOperationCompleted(object arg) {
            if ((this.OperationByIdInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperationByIdInvokeCompleted(this, new OperationByIdInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceIntegrator/OperationByNameInvoke", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet OperationByNameInvoke([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ticket, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] operationNames, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")] OperationValue[] requestParamValues) {
            object[] results = this.Invoke("OperationByNameInvoke", new object[] {
                        ticket,
                        operationNames,
                        requestParamValues});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OperationByNameInvokeAsync(string ticket, string[] operationNames, OperationValue[] requestParamValues) {
            this.OperationByNameInvokeAsync(ticket, operationNames, requestParamValues, null);
        }
        
        /// <remarks/>
        public void OperationByNameInvokeAsync(string ticket, string[] operationNames, OperationValue[] requestParamValues, object userState) {
            if ((this.OperationByNameInvokeOperationCompleted == null)) {
                this.OperationByNameInvokeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOperationByNameInvokeOperationCompleted);
            }
            this.InvokeAsync("OperationByNameInvoke", new object[] {
                        ticket,
                        operationNames,
                        requestParamValues}, this.OperationByNameInvokeOperationCompleted, userState);
        }
        
        private void OnOperationByNameInvokeOperationCompleted(object arg) {
            if ((this.OperationByNameInvokeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OperationByNameInvokeCompleted(this, new OperationByNameInvokeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServiceIntegrator/GetAuthorizationTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetAuthorizationTicket([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("GetAuthorizationTicket", new object[] {
                        login,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAuthorizationTicketAsync(string login, string password) {
            this.GetAuthorizationTicketAsync(login, password, null);
        }
        
        /// <remarks/>
        public void GetAuthorizationTicketAsync(string login, string password, object userState) {
            if ((this.GetAuthorizationTicketOperationCompleted == null)) {
                this.GetAuthorizationTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAuthorizationTicketOperationCompleted);
            }
            this.InvokeAsync("GetAuthorizationTicket", new object[] {
                        login,
                        password}, this.GetAuthorizationTicketOperationCompleted, userState);
        }
        
        private void OnGetAuthorizationTicketOperationCompleted(object arg) {
            if ((this.GetAuthorizationTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAuthorizationTicketCompleted(this, new GetAuthorizationTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")]
    public partial class Operation {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private int sqlCommandTimeoutSecondsField;
        
        private bool sqlCommandTimeoutSecondsFieldSpecified;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int SqlCommandTimeoutSeconds {
            get {
                return this.sqlCommandTimeoutSecondsField;
            }
            set {
                this.sqlCommandTimeoutSecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SqlCommandTimeoutSecondsSpecified {
            get {
                return this.sqlCommandTimeoutSecondsFieldSpecified;
            }
            set {
                this.sqlCommandTimeoutSecondsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")]
    public partial class OperationValue {
        
        private string nameParamField;
        
        private int operationIdField;
        
        private bool operationIdFieldSpecified;
        
        private string valueField;
        
        private SqlDbType valueTypeField;
        
        private bool valueTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameParam {
            get {
                return this.nameParamField;
            }
            set {
                this.nameParamField = value;
            }
        }
        
        /// <remarks/>
        public int OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationIdSpecified {
            get {
                return this.operationIdFieldSpecified;
            }
            set {
                this.operationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public SqlDbType ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueTypeSpecified {
            get {
                return this.valueTypeFieldSpecified;
            }
            set {
                this.valueTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    public enum SqlDbType {
        
        /// <remarks/>
        BigInt,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        Bit,
        
        /// <remarks/>
        Char,
        
        /// <remarks/>
        DateTime,
        
        /// <remarks/>
        Decimal,
        
        /// <remarks/>
        Float,
        
        /// <remarks/>
        Image,
        
        /// <remarks/>
        Int,
        
        /// <remarks/>
        Money,
        
        /// <remarks/>
        NChar,
        
        /// <remarks/>
        NText,
        
        /// <remarks/>
        NVarChar,
        
        /// <remarks/>
        Real,
        
        /// <remarks/>
        UniqueIdentifier,
        
        /// <remarks/>
        SmallDateTime,
        
        /// <remarks/>
        SmallInt,
        
        /// <remarks/>
        SmallMoney,
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Timestamp,
        
        /// <remarks/>
        TinyInt,
        
        /// <remarks/>
        VarBinary,
        
        /// <remarks/>
        VarChar,
        
        /// <remarks/>
        Variant,
        
        /// <remarks/>
        Xml,
        
        /// <remarks/>
        Udt,
        
        /// <remarks/>
        Structured,
        
        /// <remarks/>
        Date,
        
        /// <remarks/>
        Time,
        
        /// <remarks/>
        DateTime2,
        
        /// <remarks/>
        DateTimeOffset,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsintegrator.Data")]
    public partial class OperationParam {
        
        private string nameParamField;
        
        private int operationIdField;
        
        private bool operationIdFieldSpecified;
        
        private SqlDbType valueTypeField;
        
        private bool valueTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NameParam {
            get {
                return this.nameParamField;
            }
            set {
                this.nameParamField = value;
            }
        }
        
        /// <remarks/>
        public int OperationId {
            get {
                return this.operationIdField;
            }
            set {
                this.operationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationIdSpecified {
            get {
                return this.operationIdFieldSpecified;
            }
            set {
                this.operationIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SqlDbType ValueType {
            get {
                return this.valueTypeField;
            }
            set {
                this.valueTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueTypeSpecified {
            get {
                return this.valueTypeFieldSpecified;
            }
            set {
                this.valueTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetOperationsCompletedEventHandler(object sender, GetOperationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOperationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOperationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Operation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Operation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetOperationParamsCompletedEventHandler(object sender, GetOperationParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOperationParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOperationParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OperationParam[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OperationParam[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OperationByIdInvokeCompletedEventHandler(object sender, OperationByIdInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationByIdInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperationByIdInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void OperationByNameInvokeCompletedEventHandler(object sender, OperationByNameInvokeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationByNameInvokeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OperationByNameInvokeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAuthorizationTicketCompletedEventHandler(object sender, GetAuthorizationTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAuthorizationTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAuthorizationTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591